# Nginx
# VERSION               1.1.0

FROM app_nginx_server:1.0.0

LABEL nginx based app

RUN groupadd -r dockeradm && useradd -r -g dockeradm dockeradm 
RUN mkdir /LOGS && mkdir -p /APP/HTML/
RUN chown -R dockeradm:dockeradm /var/run/nginx.pid && chown -R dockeradm:dockeradm /LOGS && chown -R dockeradm:dockeradm /APP/*

USER dockeradm

WORKDIR /etc/nginx


